apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-factory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bluescreen/mini-factory.git
    targetRevision: main
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: mini-factory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
